name: Scrape TNT News

on:
  schedule:
    - cron: "0 */4 * * *"  # every 4 hours
  workflow_dispatch:       # manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        run: python scrapper.py

      - name: Commit Scraped Data
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add tnt_news.json
          git commit -m "Update news data"
          git push
